[entities]	 
ischaemic_stroke
haemorrhagic_stroke
stroke
mening_tumour
metast_tumour
glioma_tumour
tumour
subdural_haematoma
small_vessel_disease
atrophy
microhaemorrhage
subarachnoid_haemorrhage
haemorrhagic_transformation
loc_deep
loc_cortical
time_old
time_recent
label_yes
lr
fb

[relations]

mod-loc	Arg1:ischaemic_stroke, Arg2:loc_deep
mod-loc	Arg1:ischaemic_stroke, Arg2:loc_cortical
mod-loc	Arg1:haemorrhagic_stroke, Arg2:loc_deep
mod-loc	Arg1:haemorrhagic_stroke, Arg2:loc_cortical
mod-loc	Arg1:stroke, Arg2:loc_deep
mod-loc	Arg1:stroke, Arg2:loc_cortical
mod-loc	Arg1:microhaemorrhage, Arg2:loc_deep
mod-loc	Arg1:microhaemorrhage, Arg2:loc_cortical

mod-time	Arg1:ischaemic_stroke, Arg2:time_old
mod-time	Arg1:ischaemic_stroke, Arg2:time_recent
mod-time	Arg1:haemorrhagic_stroke, Arg2:time_old
mod-time	Arg1:haemorrhagic_stroke, Arg2:time_recent
mod-time	Arg1:stroke, Arg2:time_old
mod-time	Arg1:stroke, Arg2:time_recent
mod-time	Arg1:microhaemorrhage, Arg2:time_old
mod-time	Arg1:microhaemorrhage, Arg2:time_recent

lr-loc		Arg1:lr, Arg2:loc_deep
lr-loc		Arg1:lr, Arg2:loc_cortical
fb-loc		Arg1:fb, Arg2:loc_deep
fb-loc		Arg1:fb, Arg2:loc_cortical

#<OVERLAP> Arg1:small_vessel_disease, Arg2:subdural_haematoma, <OVL-TYPE>:contain|cross
<OVERLAP> Arg1:time_recent, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal
<OVERLAP> Arg1:time_old, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal
<OVERLAP> Arg1:loc_deep, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal
<OVERLAP> Arg1:loc_cortical, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal
<OVERLAP> Arg1:lr, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal
<OVERLAP> Arg1:fb, Arg2:<ENTITY>, <OVL-TYPE>:contain|equal

[events]

[attributes]
negated Arg:ischaemic_stroke|haemorrhagic_stroke|stroke|mening_tumour|metast_tumour|glioma_tumour|tumour|subdural_haematoma|small_vessel_disease|atrophy|microhaemorrhage|subarachnoid_haemorrhage|haemorrhagic_transformation|loc_deep|loc_cortical|time_old|time_recent

# locations
# pathol
MCA Arg:loc_deep|loc_cortical
PCA Arg:loc_deep|loc_cortical
borderzone Arg:loc_deep|loc_cortical
anterior_circ Arg:loc_deep|loc_cortical
PICA Arg:loc_deep|loc_cortical
vertebrobasilar_circ Arg:loc_deep|loc_cortical
# cortical Arg:loc_deep|loc_cortical
cortical Arg:loc_deep|loc_cortical
frontal Arg:loc_deep|loc_cortical
parietal Arg:loc_deep|loc_cortical
occipital Arg:loc_deep|loc_cortical
temporal Arg:loc_deep|loc_cortical
fronto_parietal Arg:loc_deep|loc_cortical
insular_cortex Arg:loc_deep|loc_cortical
temporo_parietal Arg:loc_deep|loc_cortical
parietal_occipital Arg:loc_deep|loc_cortical
fronto_temporal Arg:loc_deep|loc_cortical
# deep
lacunar Arg:loc_deep|loc_cortical
basal_ganglia Arg:loc_deep|loc_cortical
caudate Arg:loc_deep|loc_cortical
lentiform_nucleus Arg:loc_deep|loc_cortical
thalamus Arg:loc_deep|loc_cortical
deep Arg:loc_deep|loc_cortical
subcortical Arg:loc_deep|loc_cortical
brainstem Arg:loc_deep|loc_cortical
cerebellar Arg:loc_deep|loc_cortical
# white matter
corona_rad Arg:loc_deep|loc_cortical
ext_capsule Arg:loc_deep|loc_cortical
int_capsule Arg:loc_deep|loc_cortical
centrum_semiovale Arg:loc_deep|loc_cortical
corpus_callosum Arg:loc_deep|loc_cortical
periventricular Arg:loc_deep|loc_cortical

# This is a comment line.