bg
[labels]
ischaemic_stroke | ischaemic stroke
haemorrhagic_stroke | haemorrhagic stroke
stroke | stroke (unknown type) 
mening_tumour | tumour: meningioma
metast_tumour | tumour: metastasis
glioma_tumour | tumour: glioma
tumour
subdural_haematoma | subdural haematoma
small_vessel_disease | small vessel disease
atrophy
microhaemorrhage | microbleed
subarachnoid_haemorrhage | subarachnoid haemorrhage
haemorrhagic_transformation | haemorrhagic transformation
loc_deep | loc:deep
loc_cortical | loc:cortical
time_old | time: old
time_recent | time:recent
label_yes | yes
lr
fb

[drawing]        
SPAN_DEFAULT     fgColor:black, bgColor:lightgreen, borderColor:darken
ARC_DEFAULT      color:black, dashArray:-, arrowHead:none
ischaemic_stroke bgColor:#FFCCFF, borderColor:darken
haemorrhagic_stroke	bgColor:#009999, borderColor:darken
stroke	bgColor:#FF8533, borderColor:darken
mening_tumour			bgColor:#0000CC, borderColor:darken
metast_tumour			bgColor:#0000CC, borderColor:darken
glioma_tumour			bgColor:#0000CC, borderColor:darken
tumour			bgColor:#0000CC, borderColor:darken
subdural_haematoma	bgColor:#BB88FF, borderColor:darken
small_vessel_disease	bgColor:#FFFF99, borderColor:darken
atrophy			bgColor:#99FF99, borderColor:darken
microhaemorrhage	bgColor:#CCFFFF, borderColor:darken
subarachnoid_haemorrhage	bgColor:#FFDDFF, borderColor:darken
haemorrhagic_transformation	bgColor:#CCFF00, borderColor:darken
loc_deep		bgColor:#FF3333, borderColor:darken
loc_cortical		bgColor:#3399FF, borderColor:darken
time_old		bgColor:#00CC00, borderColor:darken
time_recent		bgColor:#FFCC00, borderColor:darken
label_yes	bgColor:#00CCFF, borderColor:darken
lr		 bgColor:#996600
fb		 bgColor:#CC9900
annotated	 bgColor:grey
negated	  	 box:crossed
#locations
# pathol
MCA glyph:(mca), position:right
PCA glyph:(pca), position:right
borderzone glyph:(borderzone), position:right
anterior_circ glyph:(anterior_circ), position:right
PICA glyph:(pica), position:right
vertebrobasilar_circ glyph:(vertebrobasilar), position:right
# cortical
cortical glyph:(cortical), position:right
frontal glyph:(frontal), position:right
parietal glyph:(parietal), position:right
occipital glyph:(occipital), position:right
temporal glyph:(temporal), position:right
fronto_parietal glyph:(fronto_parietal), position:right
insular_cortex glyph:(insular_cortex), position:right
temporo_parietal glyph:(temporo_parietal), position:right
parietal_occipital glyph:(parietal_occipital), position:right
fronto_temporal glyph:(fronto_temporal), position:right
# deep
lacunar glyph:(lacunar), position:right
basal_ganglia glyph:(basal_ganglia), position:right
caudate glyph:(caudate), position:right
lentiform_nucleus glyph:(lentiform_nucleus), position:right
thalamus glyph:(thalamus), position:right
deep glyph:(deep), position:right
subcortical glyph:(subcortical), position:right
brainstem glyph:(brainstem), position:right
cerebellar glyph:(cerebellar), position:right
# white matter
corona_rad glyph:(corona_rad), position:right
ext_capsule glyph:(ext_capsule), position:right
int_capsule glyph:(int_capsule), position:right
centrum_semiovale glyph:(centrum_semiovale), position:right
corpus_callosum glyph:(corpus_callosum), position:right
periventricular glyph:(periventricular), position:right

