#!/bin/sh

usage="makebratformat -d dirforfiles <input"

descr="Convert to brat format by splitting into individual files, converting them to -ann.xml format and then converting -ann.xml files to brat .ann and .txt files."

. `dirname $0`/setup

while [ $# -gt 0 ]; do
  arg=$1
  shift
  case $arg in
    -d)
      dir=$1
      shift
      ;;
    *)
      echo "usage: $usage" >&2
      exit 2
  esac
done

if [ $# -ne -0 -o -z "$dir" ]; then
  echo "usage: $usage" >&2
  exit 2
fi

if  [ ! -x "$dir" ]
then
    mkdir $dir
fi

lib=$here/lib/annot

cat >$dir/input


# Split into individual files.

(cd $dir ; cat input | lxt -s $here/lib/annot/splitfile.xsl ; rm input)


# Make -ann.xml files from the individual files.

for f in $dir/*[0-9].xml 
do 

fname=`basename $f .xml`

cat $f |
lxt -s $here/lib/annot/makeannot.xsl |
lxreplace -q "s//ent" >$dir/$fname-ann.xml

done


# Make brat files from -ann.xml files

for f in $dir/*-ann.xml 
do 

fname=`basename $f -ann.xml`

cat $f |
xml-to-brat $dir/$fname 

done
