#!/bin/sh
usage="score-ltg -g gold-dir -s sys-dir -d detail-dir >output.xml"
descr="Score LTG documents"

. `dirname $0`/setup

goldfile=''
sysfile=''
detaildir=''
htmlopt=''
while [ $# -gt 0 ]; do
    arg=$1
    shift
    case $arg in
        -g)
        goldfile=$1
        shift
        ;;
        -s)
        sysfile=$1
        shift
        ;;
        -d)
        detaildir=$1
        shift
        ;;
        -h)
        htmlopt='-h'
        ;;
        *)
        echo "usage: $usage" >&2
        exit 2
    esac
done

if [ "$sysfile" == "" ]
then
    echo "usage: $usage" >&2
    exit 2
fi

if [ "$goldfile" == "" ]
then
    echo "usage: $usage" >&2
    exit 2
fi

if [ "$detaildir" == "" ]
then
    echo "usage: $usage" >&2
    exit 2
fi

lib=$here/lib/ltg-jdm

classpath=$lib/bin$(find $here/lib/java -name "*.jar" | sed -n '/.*jar$/ s//:&/p' | tr -d '\n')

$LOCAL_JAVA -Xms512m -Xmx1024m -classpath "$classpath" uk.ac.ed.ltg.jdm.commands.ScoreLTGDocuments $htmlopt -g$goldfile -a$sysfile -d$detaildir -o$tmp-ltg-results.xml > $tmp-javaout 2> $tmp-javaerr || { cat $tmp-javaerr >&2; exit 1; }
cat $tmp-ltg-results.xml
